VAF client creates default configuration

diff --git a/usr/bin/vaf-enter b/usr/bin/vaf-enter
--- a/usr/bin/vaf-enter
+++ b/usr/bin/vaf-enter
@@ -70,6 +70,8 @@ export VafDebug
 export ErrArgs=1
 export ErrLocalCf=2
 export ErrKey=3
+export ErrDefaultCf=4
+export ErrUpdateCf=5
 
 # Configuration search path (colon-separated)
 export ConfPath=/etc/vaf/default:$(A=`dirname "$0"`;A=`dirname "$A"`;echo "$A/etc"):"$HOME/.vaf"
@@ -250,6 +252,16 @@ function vafwait() {
   done
 }
 
+# Find the specified configuration file. Usage:
+#   FindConf [-f] <source_cf>
+#
+# -f rises an error also when file is not found. Returns 0 on success, nonzero
+# on error
+function FindConf() {
+  HandleConf "$@" '' find
+  return $?
+}
+
 # Loads (sources) the specified configuration file. Usage:
 #   LoadConf [-f] <source_cf>
 #
@@ -343,6 +355,9 @@ function HandleConf() {
         "$Cf" >> "$Out"
         echo '' >> "$Out"
       ;;
+      find)
+        echo "$Cf"
+      ;;
     esac
 
   else
@@ -418,6 +433,31 @@ function Main() {
   #
   # Local environment
   #
+
+  # Check if vaf.conf exists in the home directory. If it does not, create a
+  # default one and exit immediately.
+
+  local VafUserConf VafUserConfDest VafUserConfExample
+
+  VafUserConfDest="$HOME/.vaf/vaf.conf"
+  VafUserConf=$( FindConf -f 'vaf.conf' )
+  if [ $? == 1 ] ; then
+    _vaf_p "VAF configuration file not found."
+    VafUserConfExample=$( FindConf -f 'vaf.conf.example' )
+    if [ $? == 1 ] ; then
+      _vaf_p "Please create a $VafUserConfDest file with your settings."
+      exit $ErrDefaultCf
+    elif ! mkdir -p $(dirname "$VafUserConfDest") > /dev/null 2>&1 ; then
+      _vaf_p "Problems creating $(dirname "$VafUserConfDest")."
+      exit $ErrDefaultCf
+    elif ! cp "$VafUserConfExample" "$VafUserConfDest" > /dev/null 2>&1 ; then
+      _vaf_p "Problems copying $VafUserConfExample to $VafUserConfDest"
+      exit $ErrDefaultCf
+    fi
+    _vaf_p "A default one has been created in $VafUserConfDest."
+    _vaf_p "Edit it to your needs and run vaf-enter again."
+    exit $ErrUpdateCf
+  fi
 
   # Before PoD
   local ConfLocalPre=( 'common.before' 'vaf.conf' 'local.before' 'local.conf' )
